# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
use_bioc: true
bioc_required: true
r:
    - release
    - devel
r_packages:
    - covr
r_github_packages:
    - venelin/PCMBase
after_success:
    - Rscript -e 'covr::codecov()'
